"""remove unnecessary field

Revision ID: ed5f89693344
Revises: 45538e49faf3
Create Date: 2026-03-09 15:38:11.408480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed5f89693344'
down_revision: Union[str, Sequence[str], None] = '45538e49faf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_subscriptions_stripe_price_id_key'), 'user_subscriptions', type_='unique')
    op.drop_column('user_subscriptions', 'stripe_price_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscriptions', sa.Column('stripe_price_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('user_subscriptions_stripe_price_id_key'), 'user_subscriptions', ['stripe_price_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
