"""add new column cancel_at_period_end

Revision ID: 2de60d9e661d
Revises: adb8a5ad25bb
Create Date: 2026-03-18 13:23:30.435697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2de60d9e661d'
down_revision: Union[str, Sequence[str], None] = 'adb8a5ad25bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscriptions', sa.Column('cancel_at_period_end', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_subscriptions', 'cancel_at_period_end')
    # ### end Alembic commands ###
