"""add missing field price_id

Revision ID: 45538e49faf3
Revises: 936550aedf45
Create Date: 2026-03-09 15:33:55.627318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45538e49faf3'
down_revision: Union[str, Sequence[str], None] = '936550aedf45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscriptions', sa.Column('stripe_price_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user_subscriptions', ['stripe_price_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_subscriptions', type_='unique')
    op.drop_column('user_subscriptions', 'stripe_price_id')
    # ### end Alembic commands ###
